#!/bin/sh
###
# Deploy a new version to chefcito.dev01.glue.gl
#
###

app_name='chefcito'
app_repository='origin'
app_branch='development'

app_gluerokku_name='chefcito'
app_gluerokku_env='development'
app_gluerokku_repository='deploy'

check_dir() {
	current_dir="$(pwd | awk -F/ '{ print $NF }')"
	if [[ $current_dir != $app_name ]]; then
		echo "Invalid directory $current_dir, go to the $app_name app root"
		exit 1
	fi
}

color_1='\033[0;33m'
color_2='\033[1;33m'
color_no='\033[0m'
color_icon=$'\360\237\215\213'

check_dir
echo "${color_icon}  ${color_1}===> ${color_2}Update${color_no}"
git checkout $app_branch || exit 1
git pull $app_repository || exit 1
echo "${color_icon}  ${color_1}===> ${color_2}Build${color_no}"
grunt $app_gluerokku_env || exit 1
echo "${color_icon}  ${color_1}===> ${color_2}Test${color_no}"
grunt test || exit 1
echo "${color_icon}  ${color_1}===> ${color_2}Deploy${color_no}"
git push $app_gluerokku_repository $app_branch:master || exit 1
echo "${color_icon}  ${color_1}===> ${color_2}Done!${color_no}"